### PR TITLE
Extract strings from zcml

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes issue #28

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Note that this cherry-picks a commit from pull request #30 for using lxml.

**Comment by vincentfretin** [comment]
Thanks @mauritsvanrees, that was quick. :) I'll test that this weekend.

**Comment by gforcada** [comment]
:+1: thanks for working on this!

@vincentfretin any other files that would still need the -manual.pot files that should also be covered by i18ndude?

**Comment by vincentfretin** [comment]
@gforcada I still need the plone-manual.pot for the mime types and the roles

@mauritsvanrees With this branch, I can extract 25 more messages which is great. But it seems that some messages are not extracted. If I remove all the manual messages (the one with configure.zcml is the comment) from plone-manual.pot and reexecute ``bin/i18n plone`` I should still have them in the po files. It's unfortunately not the case for all. And I don't know how @claytonc was able to extract messages from plone.app.contenttypes/plone/app/contenttypes/behaviors/configure.zcml in the first place. (https://github.com/collective/plone.app.locales/pull/79)

**Comment by vincentfretin** [comment]
I'm veryfying each message one by one.

**Comment by vincentfretin** [comment]
title and description from plone:behaviour, plone:ruleAction and plone:ruleCondition and name from interface directive are not extracted.

A good implementation would be to look for each directive definition and look if some attribute are MessageID, see for example parts/packages/plone/behavior/metaconfigure.py title and description are MessageID fields.

**Comment by vincentfretin** [comment]
messages from gs:registerProfile (./plone.resource/plone/resource/profiles.zcml) are not extracted. If I change the namespace to genericsetup, it works, but I will not commit this change.

**Comment by vincentfretin** [comment]
I verified all messages from plone-manual.pot and cleaned up the file. The remaining issues are the one I described in my last two comments.

**Comment by mauritsvanrees** [comment]
Using `gs` or `genericsetup` does not matter. I can extract the string from plone.resource zcml just fine:

```
$ bin/i18ndude rebuild-pot --pot plone.pot --create plone src/plone.resource/plone/resource/
$ cat plone.pot 
...
#: plone.resource/plone/resource/profiles.zcml:14
msgid "A folder for storing and serving static resource files"
msgstr ""

#: plone.resource/plone/resource/profiles.zcml:14
msgid "Static resource storage"
msgstr ""
```

But note that looking for strings only in zcml is not working for some reason:

```
$ bin/i18ndude rebuild-pot --pot plone.pot --create plone src/plone.resource/plone/resource/profiles.zcml
No entries for domain "plone".
```
I think this is an old problem, not only for zcml. I'll have a look.

**Comment by mauritsvanrees** [comment]
@vincentfretin I have updated the `find_files` method. This now extracts two msgids for the profile, even though the directive is `gs:registerProfile`:

```
bin/i18ndude rebuild-pot --pot plone.pot --create \
  plone src/plone.resource/plone/resource/profiles.zcml
```

Does that part work for you now.

**Comment by mauritsvanrees** [comment]
If we want to look for MessageIDs in for example parts/packages/plone/behavior/metaconfigure.py, then the i18ndude script would need to have access to all Plone packages and basically start up Plone and parse all the zcml looking for this. I don't think that is going to be very workable.

I have updated the pull request to simply extract all titles and descriptions from zcml, except from the upgrade steps as we know they are not translatable. This covers the other GenericSetup directives, plus the ones you mention above: plone:behavior, plone:ruleAction and plone:ruleCondition. Does that sound like a good idea.

**Comment by vincentfretin** [comment]
Ok. 83 added, 18 removed
- you should ignore title for permission directive, and any attributes on gs:exportStep, gs:importStep
- title and description from plone:ruleAction and plone:ruleCondition are not extracted. Only plone:behavior is ok.
- extract name from interface directive only if type="plone.contentrules.rule.interfaces.IRuleEventType" or if just type is set? (it's for  ./plone.app.contentrules/plone/app/contentrules/configure.zcml)

**Comment by mauritsvanrees** [comment]
> you should ignore title for permission directive, and any attributes on gs:exportStep, gs:importStep

Done.

> title and description from plone:ruleAction and plone:ruleCondition are not extracted. Only plone:behavior is ok.

In files that have this, we need to add `i18n_domain="plone"`.

> extract name from interface directive only if type="plone.contentrules.rule.interfaces.IRuleEventType" or if just type is set? (it's for ./plone.app.contentrules/plone/app/contentrules/configure.zcml)

Done for that specific type.

**Comment by mauritsvanrees** [comment]
Note: I have rebased and force pushed, to avoid a small conflicts with master.

**Comment by vincentfretin** [comment]
Very good changes @mauritsvanrees 
We can ignore monkey:patch description as well and this will be perfect. see plone.app.discussion/plone/app/discussion/configure.zcml where there is one.

**Comment by mauritsvanrees** [comment]
I am ignoring the monkey:patch description now.

Note that before this, the detected message id was:

```
This allows Catalog Tool to find comments                      during clear-and-rebuild catalog
```

For the monkey patch description it is irrelevant now, but for others it might be better to put a description on one line.  Grepping for three spaces in the plone.pot file I see for example https://github.com/plone/plone.app.contentmenu/blob/2.1.6/plone/app/contentmenu/configure.zcml#L112 where a multiline description is used, though I am not sure if this specific one is ending up somewhere user visible

**Comment by vincentfretin** [comment]
Yeah, I saw that line in plone.app.contentmenu. I don't think it's used, but I prefer not to blacklist this menu directive, it could be used in other addons and be really used.

**Comment by mauritsvanrees** [comment]
Oh, definitely not blacklist that one no. It's just that in similar cases we will want to have the description on one line, to avoid the multiple spaces.

**Pull request merged**
