### PR TITLE
Untranslated fixups

### PR DESCRIPTION
**Pull request by mauritsvanrees**
WIP Work in progress. The tests are expected to fail now, which is exactly what I want to see now.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
This is an addition for the changes I did for issue #15. Those changes had the side effects of handling the  `tal:condition/content/replace` checks less good, which is what I had fixed in release 3.4.4.  Now constructions like `<tal:block condition=...` were not recognised correctly.  This pull request fixes it and adds some more tests, including actually running the find-untranslated command on Travis.

I did not add a changelog entry, because this is a feature that was broken and fixed in the current release that we are working on.

Ready for review. And then it is about time for a 3.5.0 release I would say.

**Comment by mauritsvanrees** [comment]
@vincentfretin @ale-rt If you want to review this, that would be great.

**Comment by vincentfretin** [comment]
I tested this branch and master with all plone packages (in coredev: `bin/buildout -c experimental/i18n.cfg;bin/i18n-find-untranslated details`, this fixed several false positive like:

    <tal:comment replace="nothing">something</tal:comment>
    <metal:file use-macro="context/widgets/image/macros/image_view">download link</metal:file>
    <span tal:content="size">size</span>
    <span tal:replace="size">size</span>

No other regression.
So LGTM.

**Comment by vincentfretin** [comment]
The lines are off. For example:

    plone.protect/plone/protect/confirm.pt:34:10:
    -ERROR- - value attribute of <... submit/button> lacks i18n:attribute

Actually it's line 41, not 34. I'll test with the latest release to see if this is a regression.

**Comment by vincentfretin** [comment]
With i18ndude 3.4.5, it's line 41, so there is a regression between 3.4.5 and master.

**Comment by vincentfretin** [comment]
The regression is in commit "Use lxml instead of our home grown `common.prepare_xml`" 2015-11-11 23:04 9ebfa034987cc358ea0f78637ec2db41ab0e4975

**Comment by mauritsvanrees** [comment]
That is tricky. Let me merge this pull request, as the regression was not introduced by this branch.

**Pull request merged**
