### PR TITLE
The list command was wrongly showing 100% translated

### PR DESCRIPTION
**Pull request by vincentfretin**
This fixes i18n stats for Plone
https://github.com/plone/Products.CMFPlone/issues/3131

### CODE REVIEW

**Comment by vincentfretin** [comment]
This lie is 12 years old. :)

**Comment by vincentfretin** [comment]
@mauritsvanrees Once this is merged and released, can you please update the i18ndude version in buildout.coredev 5.2? Thanks.

**Comment by mauritsvanrees** [comment]
Gives a different meaning to "We are the 99 percent..." ;-)

**Comment by mauritsvanrees** [comment]
I have released `i18ndude 5.3.4` and updated coredev 5.2.

**Comment by vincentfretin** [comment]
Thanks!
For plone.po 1% is 33 messages not translated. :)

**Pull request merged**
